/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIInsight: typeof import('./src/components/AIAnalysis/AIInsight.vue')['default']
    ChartWidget: typeof import('./src/components/Dashboard/ChartWidget.vue')['default']
    GridLayout: typeof import('./src/components/Dashboard/GridLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VirtualTable: typeof import('./src/components/DataTable/VirtualTable.vue')['default']
  }
}
