/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIInsight: typeof import('./src/components/AIAnalysis/AIInsight.vue')['default']
    BaseChart: typeof import('./src/components/Charts/BaseChart.vue')['default']
    ChartConfigDialog: typeof import('./src/components/Charts/ChartConfigDialog.vue')['default']
    ChartWidget: typeof import('./src/components/Dashboard/ChartWidget.vue')['default']
    ElSplitter: typeof import('element-plus/es')['ElSplitter']
    ElSplitterPanel: typeof import('element-plus/es')['ElSplitterPanel']
    GridLayout: typeof import('./src/components/Dashboard/GridLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VirtualTable: typeof import('./src/components/DataTable/VirtualTable.vue')['default']
  }
}
